apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
data:
  URLS_SELF_ISSUER: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}/'
  URLS_CONSENT: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/consent'
  URLS_LOGIN: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/login'