{{- $root := . -}}

{{- range .Values.services }}
{{- if .flask_secret }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-system-secret
type: Opaque
data:
  SECRET: {{ randAlphaNum 20 | b64enc }}

{{- end }}
{{- end }}