
---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-master-secret
type: Opaque
data:
  USERNAME: {{ randAlphaNum 20 | b64enc }}
  PASSWORD: {{ randAlphaNum 20 | b64enc }}

  
{{- $root := . -}}
{{- range .Values.services }}

{{- if .database }}

---

{{- $name := printf "%s-service" .name }}
{{- $db := printf "%s-db" $name | replace "-" "_" -}}
{{- $user := printf "%s-user" $name | replace "-" "_" -}}
{{- $secret := randAlphaNum 20 -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-db-secret
type: Opaque
data:
  USERNAME: {{ $user | b64enc }}
  PASSWORD: {{ $secret | b64enc }}
  DATABASE: {{ $db | b64enc }}
  DATABASE_URI: {{ printf "postgres://%s:%s@postgres:5432/%s?sslmode=disable" $user $secret $db | b64enc }}

{{- end }}
{{- end }}

