
{{- $root := . -}}
{{- range .Values.services }}

{{- if .hydra_client }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-hydra-secret
type: Opaque
data:
  HYDRA_CLIENT_ID: {{ randAlphaNum 20 | b64enc }}
  HYDRA_CLIENT_SECRET: {{ randAlphaNum 20 | b64enc }}

{{- end }}
{{- end }}