trigger:
  - master
  - preprod
  - test
  - develop

pr: none

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      endpoint: project-origin
      name: project-origin/pipeline-templates

variables:
  - name: releaseName
    value: 'base-setup'
  - name: imageName
    value: 'projectorigin/$(releaseName)'
  - template: vars.yml@templates

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: testOutput
    steps:
      - script: |
          echo $(poolName)
      - script: |
          echo ${{ variables['poolName'] }}
  - template: job-deploy.yml@templates
    parameters:
      kubeCon: $(kubeCon)
      namespace: $(namespace)
      releaseName: $(releaseName)
      deploymentEnvironment: $(deploymentEnvironment)
      secureFileName: $(secureFileName)
      pool:
        ${{ if ne(variables['poolName'], '') }}:
          name: $(poolName)
        ${{ if eq(variables['poolName'], '') }}:
          vmImage: 'ubuntu-latest'
