trigger:
  branches:
    include:
    - master
    - feature-devops
    - test
    - develop

# no PR triggers
pr: none

resources:
- repo: self

extends:
  template: simple-param.yml
  parameters:
      branchName: $(Build.SourceBranchName)