trigger:
  branches:
    include:
    - master
    - test
    - develop

# no PR triggers
pr: none

resources:
- repo: self

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    kubeCon: 'kubecon-eloprindelse-prod'
    namespace: 'cs03-project-origin-p-01'
    secureFileName: 'prod.values.yaml'
  ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
    kubeCon: 'test-kube-con'
    namespace: 'test-project-origin'
    secureFileName: 'test.values.yaml'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    kubeCon: 'dev-kube-con'
    namespace: 'dev-project-origin'
    secureFileName: 'dev.values.yaml'

jobs:  
  - job: docker_build_push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadSecureFile@1
        name: overrideFile
        inputs:
          secureFile: $(secureFileName)

      - task: HelmDeploy@0
        displayName: Helm upgrade
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: $(kubeCon)
          namespace: $(namespace)
          command: upgrade
          chartType: filepath
          chartPath: ./chart
          releaseName: base-setup
          valueFile: $(overrideFile.secureFilePath)
          install: true
          waitForExecution: true
