trigger:
  - master
  - preprod
  - test
  - develop

pr: none

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      endpoint: project-origin
      name: project-origin/pipeline-templates

variables:
  - name: releaseName
    value: 'base-setup'
  - name: imageName
    value: 'projectorigin/$(releaseName)'
  - template: vars.yml@templates

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: deploy_poolName
  condition: ne(variables['poolName'], '')
  jobs:
    - template: job-deploy.yml@templates
      parameters:
        kubeCon: $(kubeCon)
        namespace: $(namespace)
        releaseName: $(releaseName)
        deploymentEnvironment: $(deploymentEnvironment)
        secureFileName: $(secureFileName)
        pool:
          name: $(poolName)
- stage: deploy_no_poolName
  condition: eq(variables['poolName'], '')
  jobs:
    - template: job-deploy.yml@templates
      parameters:
        kubeCon: $(kubeCon)
        namespace: $(namespace)
        releaseName: $(releaseName)
        deploymentEnvironment: $(deploymentEnvironment)
        secureFileName: $(secureFileName)
        pool:
          vmImage: 'ubuntu-latest'
