trigger:
  branches:
    include:
    - master
    - test
    - develop

# no PR triggers
pr: none

resources:
- repo: self

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - group: 'production'
- ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
  - group: 'preprod'
- ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
  - group: 'develop'


jobs:  
  - deployment: helm_install
    displayName: install base setup
    pool:
      vmImage: 'ubuntu-latest'
        
    environment: $(deploymentEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: Download source

            - task: DownloadSecureFile@1
              name: overrideFile
              inputs:
                secureFile: $(secureFileName)
                
            - task: HelmDeploy@0
              displayName: Helm upgrade
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: $(kubeCon)
                namespace: $(namespace)
                command: upgrade
                chartType: filepath
                chartPath: ./chart
                releaseName: base-setup
                valueFile: $(overrideFile.secureFilePath)
                install: true
                waitForExecution: true
