trigger:
  - master
  - preprod
  - test
  - develop

pr: none

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      endpoint: project-origin
      name: project-origin/pipeline-templates

variables:
  - name: releaseName
    value: 'base-setup'
  - name: imageName
    value: 'projectorigin/$(releaseName)'
  - template: vars.yml@templates
  - template: helm-values.yml@templates

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - template: job-deploy.yml@templates
    parameters:
      kubeCon: $(kubeCon)
      namespace: $(namespace)
      releaseName: $(releaseName)
      deploymentEnvironment: $(deploymentEnvironment)
      preDeploy:
        - script:
            python3 yaml_json_converter.py yaml_to_json chart/values.yaml values.json
        - task: FileTransform@1
          inputs: 
            fileType: json
            targetFiles: values.json
        - script:
            python3 yaml_json_converter.py json_to_yaml values.json chart/values.yaml 
        - script:
            cat chart/values.yaml
      pool:
        ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
          name: $(poolName)
        ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
          vmImage: 'ubuntu-latest'
