apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        rewrite name oauth.eloprindelse.dk hydra-service.project-origin.svc.cluster.local
        rewrite name datahub.eloprindelse.dk datahub-service.project-origin.svc.cluster.local
        rewrite name account.eloprindelse.dk account-service.project-origin.svc.cluster.local
        rewrite name ledger.eloprindelse.dk hyperledger-service.project-origin.svc.cluster.local
        rewrite name api.app.eloprindelse.dk example-backend-service.project-origin.svc.cluster.local
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }