
### FLASK SECRETS
apiVersion: v1
kind: Secret
metadata:
  name: hydra-system-secret
  namespace: project-origin
type: Opaque
data:
  system-secret: ZmFzZGZhZ2hhMTI0YXJlYWZnMmRm
---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-service-system-secret
  namespace: project-origin
type: Opaque
data:
  system-secret: YXNnYWV3NHRhNGF0NDNxMzU2dWg0NTY=
---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-system-secret
  namespace: project-origin
type: Opaque
data:
  system-secret: YWZnYTRnNDV1aDc2dWk3NnM1dHl5NDU=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-service-system-secret
  namespace: project-origin
type: Opaque
data:
  system-secret: NThqcnQ1Njc4ZW43d24zNW42NDM=
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-service-system-secret
  namespace: project-origin
type: Opaque
data:
  system-secret: dDM0Z2JlaDQ1eWJoNDc2aDQ1am4=



# DB SECRETS 
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-master-secret
  namespace: project-origin
type: Opaque
data:
  username: ZXhhbXBsZS1hcHA=
  password: YWdyZXRnZTU2aDRqNjQ1ams0dzZuNDU2
---
apiVersion: v1
kind: Secret
metadata:
  name: example-app-db-secret
  namespace: project-origin
type: Opaque
data:
  username: ZXhhbXBsZV9hcHBfdXNlcg==      # example_app_user
  password: M2hhNTRoYTM0bW5hMzU0N3k2bTg3  # 3ha54ha34mna3547y6m87
  database: ZXhhbXBsZV9hcHBfZGI=          #example_app_db
  connection-string: cG9zdGdyZXM6Ly9leGFtcGxlX2FwcF91c2VyOjNoYTU0aGEzNG1uYTM1NDd5Nm04N0Bwb3N0Z3Jlczo1NDMyL2V4YW1wbGVfYXBwX2RiP3NzbG1vZGU9ZGlzYWJsZQ==
                  # postgres://example_app_user:3ha54ha34mna3547y6m87@postgres:5432/example_app_db?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-db-secret
  namespace: project-origin
type: Opaque
data:
  username: YWNjb3VudF9zZXJ2aWNlX3VzZXI=
  password: cEF6UE9DbEExODZwcDY3U3MwNE0=
  database: YWNjb3VudF9zZXJ2aWNlX2Ri
  connection-string: cG9zdGdyZXM6Ly9hY2NvdW50X3NlcnZpY2VfdXNlcjpwQXpQT0NsQTE4NnBwNjdTczA0TUBwb3N0Z3Jlczo1NDMyL2FjY291bnRfc2VydmljZV9kYj9zc2xtb2RlPWRpc2FibGU=
# postgres://account_service_user:pAzPOClA186pp67Ss04M@postgres:5432/account_service_db?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-service-db-secret
  namespace: project-origin
type: Opaque
data:
  username: ZGF0YWh1Yl9zZXJ2aWNlX3VzZXI=
  password: VDZqOHptU21VV2laeURieHFObTU=
  database: ZGF0YWh1Yl9zZXJ2aWNlX2Ri
  connection-string: cG9zdGdyZXM6Ly9kYXRhaHViX3NlcnZpY2VfdXNlcjpUNmo4em1TbVVXaVp5RGJ4cU5tNUBwb3N0Z3Jlczo1NDMyL2RhdGFodWJfc2VydmljZV9kYj9zc2xtb2RlPWRpc2FibGU=
# postgres://datahub_service_user:T6j8zmSmUWiZyDbxqNm5@postgres:5432/datahub_service_db?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: hydra-db-secret
  namespace: project-origin
type: Opaque
data:
  username: aHlkcmFfdXNlcg==
  password: eGF3S0kxdnJWTWlsbklhWXV4MXE=
  database: aHlkcmFfZGI=
  connection-string: cG9zdGdyZXM6Ly9oeWRyYV91c2VyOnhhd0tJMXZyVk1pbG5JYVl1eDFxQHBvc3RncmVzOjU0MzIvaHlkcmFfZGI/c3NsbW9kZT1kaXNhYmxl
# postgres://hydra_user:xawKI1vrVMilnIaYux1q@postgres:5432/hydra_db?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-service-db-secret
  namespace: project-origin
type: Opaque
data:
  username: aWRlbnRpdHlfc2VydmljZV91c2Vy
  password: eG5yR1I2SmdFOFNva2I5OGk2VnM=
  database: aWRlbnRpdHlfc2VydmljZV9kYg==
  connection-string: cG9zdGdyZXM6Ly9pZGVudGl0eV9zZXJ2aWNlX3VzZXI6eG5yR1I2SmdFOFNva2I5OGk2VnNAcG9zdGdyZXM6NTQzMi9pZGVudGl0eV9zZXJ2aWNlX2RiP3NzbG1vZGU9ZGlzYWJsZQ==
# postgres://identity_service_user:xnrGR6JgE8Sokb98i6Vs@postgres:5432/identity_service_db?sslmode=disable


### HYDRA CLIENTS 
---
apiVersion: v1
kind: Secret
metadata:
  name: example-app-hydra-secret
  namespace: project-origin
type: Opaque
data:
  username: ZXhhbXBsZS1hcHA=
  password: cWwwVHRseGxaRTFEVHBiYUN3OEQ=
  name: RXhhbXBsZSBBcHBsaWNhdGlvbg==
  callback: aHR0cHM6Ly9hcGkuYXBwLmVsb3ByaW5kZWxzZS5kay9hdXRoL2xvZ2luL2NhbGxiYWNr
---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-hydra-secret
  namespace: project-origin
type: Opaque
data:
  username: YWNjb3VudC1zZXJ2aWNl
  password: WHdyWXJDNkdXVGRpVlNzeG5MREI=
  name: QWNjb3VudCBTZXJ2aWNl
  callback: aHR0cHM6Ly9hY2NvdW50LmVsb3ByaW5kZWxzZS5kay9hdXRoL2xvZ2luL2NhbGxiYWNr

