apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-config
data:
  DOMAIN: {{ .Values.domain | quote }}
  DEBUG: {{ .Values.debug | quote }}
  {{- if .Values.instrumentation_key}}
  AZURE_APP_INSIGHTS_CONN_STRING: {{ .Values.instrumentation_key | quote }}
  {{- end }}