apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
data:
  URLS_SELF_ISSUER: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}/'
  URLS_CONSENT: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/consent'
  URLS_LOGIN: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/login'
  URLS_LOGOUT: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/logout'
  URLS_ERROR: '{{ .Values.protocol }}://{{ .Values.services.example_backend.ingress.subdomain }}.{{ .Values.domain }}/auth/error'
  URLS_POST_LOGOUT_REDIRECT: '{{ .Values.protocol }}://{{ .Values.services.example_frontend.ingress.subdomain }}.{{ .Values.domain }}'