apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  TOKEN_EXPIRE_MINUTES: '4320'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_URL: 'http://{{ .Values.services.hydra.name }}-service:4445'
  FAILURE_REDIRECT_URL: '{{ .Values.protocol }}://{{ .Values.services.example_frontend.ingress.subdomain }}.{{ .Values.domain }}'
  EMAIL_FROM_NAME: '{{ .Values.email.sender_name }}'
  EMAIL_FROM_ADDRESS: '{{ .Values.email.sender_address }}'
  SENDGRID_API_KEY: '{{ .Values.email.sendgrid_key }}'