apiVersion: v1
kind: ConfigMap
metadata:
  name: example-frontend-config
data:
  API_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleBackend.ingress.subdomain }}.{{ .Values.domain }}'
  AUTH_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleBackend.ingress.subdomain }}.{{ .Values.domain }}/auth/login'
  LOGOUT_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleBackend.ingress.subdomain }}.{{ .Values.domain }}/auth/logout'