apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  LOG_LEVEL: '{{ .Values.logLevel }}'
  TOKEN_EXPIRE_MINUTES: '4320'
  CONSENT_EXPIRE_MINUTES: '525600'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_URL: 'http://{{ .Values.services.hydra.name }}-service:4445'
  FAILURE_REDIRECT_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleFrontend.ingress.subdomain }}.{{ .Values.domain }}'
  EMAIL_FROM_NAME: '{{ .Values.email.senderName }}'
  EMAIL_FROM_ADDRESS: '{{ .Values.email.senderAddress }}'
  SENDGRID_API_KEY: '{{ .Values.email.sendgridKey }}'
