apiVersion: v1
kind: ConfigMap
metadata:
  name: example-backend-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  LOG_LEVEL: '{{ .Values.logLevel }}'
  CORS_ORIGINS: '{{ .Values.protocol }}://{{ .Values.services.exampleFrontend.ingress.subdomain }}.{{ .Values.domain }}'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleBackend.ingress.subdomain }}.{{ .Values.domain }}'
  FRONTEND_URL: '{{ .Values.protocol }}://{{ .Values.services.exampleFrontend.ingress.subdomain }}.{{ .Values.domain }}'
  DATAHUB_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.services.datahub.ingress.subdomain }}.{{ .Values.domain }}'
  ACCOUNT_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.services.account.ingress.subdomain }}.{{ .Values.domain }}'
  ACCOUNT_SERVICE_LOGIN_URL: '{{ .Values.protocol }}://{{ .Values.services.account.ingress.subdomain }}.{{ .Values.domain }}/auth/login'
  HYDRA_URL: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_INTROSPECT_URL: 'http://{{ .Values.services.hydra.name }}-service:4445/oauth2/introspect'
  IDENTITY_SERVICE_EDIT_PROFILE_URL: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/edit-profile'
  IDENTITY_SERVICE_EDIT_CLIENTS_URL: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/clients'
  IDENTITY_SERVICE_DISABLE_USER_URL: '{{ .Values.protocol }}://{{ .Values.services.identity.ingress.subdomain }}.{{ .Values.domain }}/disable-user'
  EMAIL_FROM_NAME: '{{ .Values.email.senderName }}'
  EMAIL_FROM_ADDRESS: '{{ .Values.email.senderAddress }}'
  EMAIL_TO_ADDRESS: '{{ .Values.email.support }}'
  EMAIL_PREFIX: 'eloprindelse - '
  SENDGRID_API_KEY: '{{ .Values.email.sendgridKey }}'
  REDIS_HOST: 'redis-service' 
  REDIS_PORT: '6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: ''
  REDIS_CACHE_DB: '0'
  REDIS_BROKER_DB: '1'
  REDIS_BACKEND_DB: '2'
