apiVersion: v1
kind: ConfigMap
metadata:
  name: datahub-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  CORS_ORIGINS: '{{ .Values.protocol }}://{{ .Values.services.exampleFrontend.ingress.subdomain }}.{{ .Values.domain }}'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.datahub.ingress.subdomain }}.{{ .Values.domain }}'
  ACCOUNT_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.services.account.ingress.subdomain }}.{{ .Values.domain }}'
  LEDGER_URL: 'http://{{ .Values.services.ledger.name }}-service'
  ENERGY_TYPE_SERVICE_URL: 'http://{{ .Values.services.energyType.name }}-service'
  HYDRA_URL: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_INTROSPECT_URL: 'http://{{ .Values.services.hydra.name }}-service:4445/oauth2/introspect'
  REDIS_HOST: 'redis-service' 
  REDIS_PORT: '6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: ''
  REDIS_CACHE_DB: '6'
  REDIS_BROKER_DB: '7'
  REDIS_BACKEND_DB: '8'
{{- if .Values.useFakeEloverblik }}
  ELOVERBLIK_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.fakeEloverblik.name }}'
  ELOVERBLIK_ONBOARDING_URL: '{{ .Values.protocol }}://{{ .Values.fakeEloverblik.name }}/onboarding'
{{ else }}
  ELOVERBLIK_SERVICE_URL: '{{ .Values.eloverblik.service }}'
  ELOVERBLIK_ONBOARDING_URL: '{{ .Values.eloverblik.onboarding }}'
{{ end }}
  ELOVERBLIK_THIRD_PARTY_ID: '{{ .Values.eloverblik.thirdpartyid }}'
  ELOVERBLIK_REQUEST_ACCESS_FROM: '{{ .Values.eloverblik.requestAccessFrom }}'
  ELOVERBLIK_REQUEST_ACCESS_TO: '{{ .Values.eloverblik.requestAccessTo }}'
{{- if .Values.firstMeasurementTime }}
  FIRST_MEASUREMENT_TIME: '{{ .Values.firstMeasurementTime }}'
{{- end }}
{{- if .Values.lastMeasurementTime }}
  LAST_MEASUREMENT_TIME: '{{ .Values.lastMeasurementTime }}'
{{- end }}

