apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_DEFAULT_INSTANCE_NAME: '{{ .Values.protocol }}://{{ .Values.services.grafana.ingress.subdomain }}.{{ .Values.domain }}/'
  GF_DATABASE_TYPE: 'postgres'
  GF_DATABASE_SSL_MODE: 'disable'