apiVersion: v1
kind: ConfigMap
metadata:
  name: datahub-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  CORS_ORIGINS: '{{ .Values.protocol }}://{{ .Values.services.example_frontend.ingress.subdomain }}.{{ .Values.domain }}'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.datahub.ingress.subdomain }}.{{ .Values.domain }}'
  ACCOUNT_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.services.account.ingress.subdomain }}.{{ .Values.domain }}'
  LEDGER_URL: 'http://{{ .Values.services.ledger.name }}-service'
  ENERGY_TYPE_SERVICE_URL: 'http://{{ .Values.services.energy_type.name }}-service'
  HYDRA_URL: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_INTROSPECT_URL: 'http://{{ .Values.services.hydra.name }}-service:4445/oauth2/introspect'
  REDIS_HOST: 'redis-service' 
  REDIS_PORT: '6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: ''
  REDIS_CACHE_DB: '6'
  REDIS_BROKER_DB: '7'
  REDIS_BACKEND_DB: '8'
  ELOVERBLIK_THIRD_PARTY_ID: '{{ .Values.eloverblik.thirdpartyid }}'
  ELOVERBLIK_SERVICE_URL: '{{ .Values.eloverblik.service }}'
  ELOVERBLIK_ONBOARDING_URL: '{{ .Values.eloverblik.onboarding }}'
  ELOVERBLIK_REQUEST_ACCESS_FROM: '2020-04-01'
  ELOVERBLIK_REQUEST_ACCESS_TO: '2020-12-31'
