apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  DATABASE_CONN_POLL_SIZE: '3'
  CORS_ORIGINS: '{{ .Values.protocol }}://{{ .Values.services.example_frontend.ingress.subdomain }}.{{ .Values.domain }}'
  PROJECT_URL: '{{ .Values.protocol }}://{{ .Values.services.account.ingress.subdomain }}.{{ .Values.domain }}'
  DATAHUB_SERVICE_URL: '{{ .Values.protocol }}://{{ .Values.services.datahub.ingress.subdomain }}.{{ .Values.domain }}'
  LEDGER_URL: 'http://{{ .Values.services.ledger.name }}-service'
  HYDRA_URL: '{{ .Values.protocol }}://{{ .Values.services.hydra.ingress.subdomain }}.{{ .Values.domain }}'
  HYDRA_INTROSPECT_URL: 'http://{{ .Values.services.hydra.name }}-service:4445/oauth2/introspect'
  REDIS_HOST: 'redis-service' 
  REDIS_PORT: '6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: ''
  REDIS_CACHE_DB: '3'
  REDIS_BROKER_DB: '4'
  REDIS_BACKEND_DB: '5'

