---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
{{- if .Values.postgres.host }}
  type: ExternalName
  externalName: {{ .Values.postgres.host | quote }}
{{- else }}
  ports:
    - port: 5432
  selector:
    app: postgres-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
      - name: postgres-container
        image: postgres:9.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-master-secret
              key: USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-master-secret
              key: PASSWORD
{{- end }}