---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
{{- if .Values.postgres.host }}
  type: ExternalName
  externalName: {{ .Values.postgres.host | quote }}
{{- else }}
  ports:
    - port: 5432
  selector:
    app: postgres-deployment
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  serviceName: "postgres-deployment"
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-container
          image: postgres:11.9
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-master-secret
                  key: USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-master-secret
                  key: PASSWORD
{{- if .Values.persistentVolumeClaims }}
{{- if .Values.persistentVolumeClaims.postgresStorageDisk }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaims.postgresStorageDisk.name }}
{{- end }}
{{- end }}
{{- end }}