{{- $root := . -}}
{{- range .Values.persistentVolumeClaims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .size }}

{{- if eq .storageClassName "manual" }}
  volumeName: {{ .name }}-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-volume
spec:
  storageClassName: manual
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .localPath }}
{{- end }}

{{- end }}
# ---


