
{{- $root := . -}}

apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: po-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

    {{- if .Values.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuer | quote }}
    {{- end }}
spec:

{{- if .Values.tls }}
  tls:
    - secretName: {{ .Values.tls.secret }}
      hosts:
{{- range .Values.services }}
{{- if .ingress }}
        - {{ .ingress.subdomain }}.{{ $root.Values.domain }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.loadBalancer }}
  controller:
    service:
      loadBalancerIP: {{ .Values.loadBalancer }}
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- end }}

  rules:
  {{- range .Values.services }}
  {{- if .ingress }}
  - host: {{ .ingress.subdomain }}.{{ $root.Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .name }}-service
          servicePort: 80
  {{- end }}
  {{- end }}