
{{- $root := . -}}

apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: po-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if $root.Values.redirectDomainTo }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = '{{ $root.Values.domain }}') {
        return 307 {{ $root.Values.redirectDomainTo }};
      }
      if ($host = 'www.{{ $root.Values.domain }}') {
        return 307 {{ $root.Values.redirectDomainTo }};
      }
    {{- end }}

    {{- if .Values.tls.issuer }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuer | quote }}
    {{- end }}
spec:
{{- if .Values.tls.secret }}
  tls:
{{- if and ($root.Values.redirectDomainTo) ($root.Values.tls.rootSecret)}}
    - secretName: {{ .Values.tls.rootSecret }}
      hosts:
        - {{ $root.Values.domain }}
{{- end }}
    - secretName: {{ .Values.tls.secret }}
      hosts:
{{- if and ($root.Values.redirectDomainTo) (not $root.Values.tls.rootSecret)}}
        - {{ $root.Values.domain }}
{{- end }}
{{- range .Values.services }}
{{- if and (.ingress) (not .tlsSecret) }}
        - {{ .ingress.subdomain }}.{{ $root.Values.domain }}
{{- end }}
{{- end }}
{{- range .Values.services }}
{{- if and (.ingress) (.tlsSecret) }}
    - secretName: {{ .tlsSecret }}
      hosts:
        - {{ .ingress.subdomain }}.{{ $root.Values.domain }}
{{- end }}
{{- end }}
{{- end }}
  rules:
  {{- if $root.Values.redirectDomainTo }}
  - host: {{ $root.Values.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: example-frontend-service
            servicePort: 80
  - host: www.{{ $root.Values.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: example-frontend-service
            servicePort: 80
  {{- end }}
  {{- range .Values.services }}
  {{- if .ingress }}
  - host: {{ .ingress.subdomain }}.{{ $root.Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .name }}-service
          servicePort: 80
  {{- end }}
  {{- end }}
