
{{- $root := . -}}

apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: po-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if $root.Values.redirect_domain_to }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = ^{{ $root.Values.domain }}$) {
        return 301 {{ $root.Values.protocol }}://{{ $root.Values.redirect_domain_to }};
      }
    {{- end }}

    {{- if .Values.tls.issuer }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuer | quote }}
    {{- end }}
spec:

{{- if .Values.tls.secret }}
  tls:
    - secretName: {{ .Values.tls.secret }}
      hosts:
{{- range .Values.services }}
{{- if .ingress }}
        - {{ .ingress.subdomain }}.{{ $root.Values.domain }}
{{- end }}
{{- end }}
{{- end }}


  rules:
  {{- range .Values.services }}
  {{- if .ingress }}
  - host: {{ .ingress.subdomain }}.{{ $root.Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .name }}-service
          servicePort: 80
  {{- end }}
  {{- end }}
