
{{- $root := . -}}
{{- range .Values.services }}
{{- $job_name := printf "create-db-%s-job" .name }}
{{- if (.database) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $job_name }}
spec:
  template:
    spec:
      containers:
      - name: create-db-{{ .name }}-container
        image: postgres:9.6
        command:
          - bash
          - -c
        args:
          - psql
            --command 
            "DROP DATABASE ${NEW_DB};"
            --command 
            "DROP USER ${NEW_USER};"
            --command 
            "CREATE USER ${NEW_USER} WITH PASSWORD '${NEW_PASS}';"
            --command 
            "GRANT ${NEW_USER} TO $(echo ${PGUSER} | cut -f1 -d@);"
            --command
            "CREATE DATABASE ${NEW_DB} OWNER ${NEW_USER};"
            --command
            "REVOKE ${NEW_USER} FROM $(echo $PGUSER | cut -f1 -d@);"
        env:
        - name: PGHOST
          value: 'postgres-service'
        - name: PGPORT 
          value: '5432' 
        - name: PGDATABASE
          value: 'postgres'
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-master-secret
              key: USERNAME
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-master-secret
              key: PASSWORD
        - name: NEW_USER
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-db-secret
              key: USERNAME
        - name: NEW_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-db-secret
              key: PASSWORD
        - name: NEW_DB
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-db-secret
              key: DATABASE
      restartPolicy: Never
  backoffLimit: 20

{{- end }}
{{- end }}