
{{- $root := . -}}
{{- range .Values.services }}

{{- if .database }}
---

{{- $secret_name := printf "%s-db-secret" .name }}
{{- $secret := (lookup "v1" "Secret" $root.Release.Namespace $secret_name) -}}

{{- $name := printf "%s-%s-service" $root.Values.postgres.prefix .name }}
{{- $db := printf "%s-db" $name | replace "-" "_" -}}
{{- $user := printf "%s-user" $name | replace "-" "_" -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
type: Opaque
data:
  USERNAME: {{ $user | b64enc }}
  DATABASE: {{ $db | b64enc }}

{{- if $secret }}
  {{ $password := printf "%s" $secret.data.PASSWORD | b64dec }}
  PASSWORD: {{ $password | b64enc }}
  DATABASE_URI: {{ printf "postgres://%s:%s@postgres-service:5432/%s?sslmode=disable" $user $password $db | b64enc }}
{{- else}}
  {{ $password := randAlphaNum 20 }}
  PASSWORD: {{ $password | b64enc }}
  DATABASE_URI: {{ printf "postgres://%s:%s@postgres-service:5432/%s?sslmode=disable" $user $password $db | b64enc }}
{{- end }}

{{- end }}
{{- end }}

