
{{- $root := . -}}
{{- range .Values.services }}

{{- if .hydraClient }}
---

{{- $secret_name := printf "%s-hydra-secret" .name }}
{{- $secret := (lookup "v1" "Secret" $root.Release.Namespace $secret_name) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
type: Opaque
data: 
{{- if $secret }}
  HYDRA_CLIENT_ID: {{ $secret.data.HYDRA_CLIENT_ID }}
  HYDRA_CLIENT_SECRET: {{ $secret.data.HYDRA_CLIENT_SECRET }}
{{- else }}
  HYDRA_CLIENT_ID: {{ randAlphaNum 20 | b64enc }}
  HYDRA_CLIENT_SECRET: {{ randAlphaNum 20 | b64enc }}
{{- end }}


{{- end }}
{{- end }}