
apiVersion: v1
kind: Secret
metadata:
  name: energy-type-secret
type: Opaque
data:
  azurestorageaccountname: '{{ .Values.storage.energy_type.name | b64enc }}'
  azurestorageaccountkey: '{{ .Values.storage.energy_type.key | b64enc }}'
  