
---

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-master-secret") -}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-master-secret
type: Opaque
data:
{{- if .Values.postgres.host }}
  USERNAME: {{ .Values.postgres.username | b64enc }}
  PASSWORD: {{ .Values.postgres.password | b64enc }}
{{- else if $secret }}
  USERNAME: {{ $secret.data.USERNAME }}
  PASSWORD: {{ $secret.data.PASSWORD }}
{{- else }}
  USERNAME: {{ randAlphaNum 20 | b64enc }}
  PASSWORD: {{ randAlphaNum 20 | b64enc }}
{{- end }}

