{{- $root := . -}}

{{- range .Values.services }}
{{- if .flaskSecret }}

---

{{- $secret_name := printf "%s-system-secret" .name }}
{{- $secret := (lookup "v1" "Secret" $root.Release.Namespace $secret_name) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
type: Opaque
data:
{{- if $secret }}
  SECRET: {{ $secret.data.SECRET }}
{{- else }}
  SECRET: {{ randAlphaNum 20 | b64enc }}
{{- end }}
  

{{- end }}
{{- end }}