{{- if eq .Values.storage.energyType.type "azureFile" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: energy-type-secret
type: Opaque
data:
  azurestorageaccountname: '{{ .Values.storage.energyType.name | b64enc }}'
  azurestorageaccountkey: '{{ .Values.storage.energyType.key | b64enc }}'
{{- end }}