
{{- $root := . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        {{- range .Values.services }}
        {{- if .hydra_client }}
        rewrite name {{ .ingress.subdomain }}.{{ $root.domain }} {{ .name }}-service.project-origin.svc.cluster.local
        {{- end }}
        {{- end }}
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }