

protocol: https
tls:
  issuer: letsencrypt-prod
  secret: eloprindelse-tls-cert

domain: alpha.eloprindelse.dk
debug: 1

instrumentation_key: InstrumentationKey=07ce92d2-e6c6-4ea0-9e95-0b2c7efe3816

services:

  account:
    name: account
    ingress: 
      subdomain: account
    database: true
    flask_secret: true
    hydra_client:
      name: "Account Service"
      callback: /auth/login/callback
    ports:
      - name: 'http'
        port: 80
        targetPort: 8085

  datahub:
    name: datahub
    ingress: 
      subdomain: datahub
    database: true
    flask_secret: true
    ports:
      - name: 'http'
        port: 80
        targetPort: 8089
  
  energy_type:
    name: energy-type
    ports:
      - name: 'http'
        port: 80
        targetPort: 8765

  example_backend:
    name: example-backend
    ingress: 
      subdomain: api.app
    database: true
    flask_secret: true
    hydra_client:
      name: "Example Backend"
      callback: /auth/login/callback
    ports:
      - name: 'http'
        port: 80
        targetPort: 8081
      - name: 'https'
        port: 443
        targetPort: 8081

  example_frontend:
    name: example-frontend
    ingress: 
      subdomain: app
    ports:
      - name: 'http'
        port: 80
        targetPort: 80

  identity:
    name: identity
    ingress: 
      subdomain: identity
    database: true
    flask_secret: true
    ports:
      - name: 'http'
        port: 80
        targetPort: 9120

  hydra:
    name: hydra
    ingress: 
      subdomain: oauth
    database: true
    flask_secret: true
    ports:
      - name: 'public-interface'
        port: 80
        targetPort: 4444
      - name: 'admin-interface'
        port: 4445
        targetPort: 4445
    
  ledger:
    name: hyperledger
    ingress: 
      subdomain: ledger
    ports:
      - name: 'http'
        port: 80
        targetPort: 8008

